# Generated by Django 4.2.4 on 2023-09-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe', models.CharField(max_length=600)),
                ('dest_name', models.CharField(max_length=256)),
            ],
        ),
    ]
