# Generated by Django 4.2.4 on 2023-09-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.CharField(max_length=256)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_dest.urls')),
            ],
        ),
    ]
